Linux compile fixes
- 'Button1', 'Button2', up through 'Button5' are #defined in
  /usr/include/X11/X.h and can't be used for variable names.  This was
  breaking compilation of PreviewModels, EffectsPanel, and TabSchedule
  under Linux.
- Add 'gl' to wx-config libs required for command line
- Add GL and GLU libraries to link command line
- TabPapagayo currently fails with a link error on
  wxGridCellEditorEvtHandler
  and I haven't found a solution yet, so this code is temporarily ifdef-ed
  out when compiling under Linux.  The error is:
  "undefined reference to `wxGridCellEditorEvtHandler::ms_classInfo'"